version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - gocritic

  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
