version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - gocritic

linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental