version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: online_queue_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - online_queue_network

  redis:
    image: redis:7
    container_name: redis

    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --databases 16 
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - online_queue_network

  migrate:
    build:
      context: .
      dockerfile: ./services/migrate/migration.Dockerfile
    container_name: online_queue_migrate
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    restart: "no"
    networks:
      - online_queue_network

  auth:
    build:
      context: .
      dockerfile: ./services/auth/auth.Dockerfile
    container_name: online_queue_auth
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      SERVICE_NAME: auth
      LOGSTASH_TCP_ADDR: logstash:5045
      OTEL_SERVICE_NAME: auth
      OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4317
    networks:
      - online_queue_network

  registration:
    build:
      context: .
      dockerfile: ./services/registration/registration.Dockerfile
    container_name: online_queue_registration
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      SERVICE_NAME: registration
      LOGSTASH_TCP_ADDR: logstash:5045
      OTEL_SERVICE_NAME: registration
      OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4317
    networks:
      - online_queue_network

  branches:
    build:
      context: .
      dockerfile: ./services/branches/branches.Dockerfile
    container_name: online_queue_branches
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      SERVICE_NAME: branches
      LOGSTASH_TCP_ADDR: logstash:5045
      OTEL_SERVICE_NAME: branches
      OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4317
    networks:
      - online_queue_network

  booking:
    build:
      context: .
      dockerfile: ./services/booking/booking.Dockerfile
    container_name: online_queue_booking
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    ports:
      - "8084:8084"
    env_file:
      - .env
    environment:
      SERVICE_NAME: booking
      LOGSTASH_TCP_ADDR: logstash:5045
      OTEL_SERVICE_NAME: booking
      OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4317
    networks:
      - online_queue_network

  scheduler:
    build:
      context: .
      dockerfile: ./services/scheduler/scheduler.Dockerfile
    container_name: online_queue_scheduler
    depends_on:
      redis:
        condition: service_healthy
      bot:
        condition: service_started
    env_file:
      - .env
    environment:
      SERVICE_NAME: scheduler
      LOGSTASH_TCP_ADDR: logstash:5045
      OTEL_SERVICE_NAME: scheduler
      OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4317
    networks:
      - online_queue_network

  bot:
    build:
      context: .
      dockerfile: ./services/bot/bot.Dockerfile
    container_name: online_queue_bot
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      SERVICE_NAME: bot
      LOGSTASH_TCP_ADDR: logstash:5045
      OTEL_SERVICE_NAME: bot
      OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4317
    networks:
      - online_queue_network

volumes:
  postgres_data:


networks:
  online_queue_network:
    name: online_queue_network
    external: true
