version: "3.9"



services:

  registration:
    build:
      context: .
      dockerfile: services/registration/registration.Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
      
  postgres:
    image: postgres:15
    container_name: online_queue_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: