input {
  http {
    port => 5044
    codec => json
    response_headers => {
      "Content-Type" => "text/plain"
    }
    response_code => 200
    add_field => { "[@metadata][source]" => "http" }
  }

  tcp {
    port => 5045
    codec => "json_lines"
    add_field => { "[@metadata][source]" => "tcp" }
  }
}

filter {
  if [time] {
    date {
      match => ["time", "ISO8601"]
      target => "@timestamp"
    }
  }

  mutate {
    add_field => {
      "project" => "online-queue"
    }
  }
}

output {
  if [@metadata][source] == "http" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "online-queue-http-logs-%{+YYYY.MM.dd}"
    }
  } else if [@metadata][source] == "tcp" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "online-queue-app-logs-%{+YYYY.MM.dd}"
    }
  }

  stdout {
    codec => rubydebug
  }
}