-- +goose Up
-- +goose StatementBegin
ALTER TABLE branches
    ADD COLUMN timezone text NOT NULL DEFAULT 'UTC';

ALTER TABLE employee_schedules
    RENAME TO employee_schedules_legacy;

CREATE TABLE employee_schedules (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id  bigint NOT NULL,
    starts_at    timestamptz NOT NULL,
    ends_at      timestamptz NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_employee_schedules_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_employee_schedules_time_range
        CHECK (starts_at < ends_at),

    CONSTRAINT uq_employee_schedule_unique_slot
        UNIQUE (employee_id, starts_at, ends_at)
);

CREATE INDEX idx_employee_schedules_employee_id
    ON employee_schedules (employee_id);

CREATE INDEX idx_employee_schedules_starts_at
    ON employee_schedules (starts_at);

CREATE INDEX idx_employee_schedules_employee_starts_at
    ON employee_schedules (employee_id, starts_at);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS employee_schedules;

ALTER TABLE employee_schedules_legacy
    RENAME TO employee_schedules;

ALTER TABLE branches
    DROP COLUMN IF EXISTS timezone;
-- +goose StatementEnd
