-- +goose Up
-- +goose StatementBegin
CREATE TABLE businesses (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    type        text NOT NULL
);

CREATE TABLE roles (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE
);

CREATE TABLE branches (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id bigint NOT NULL,
    name        text NOT NULL,
    address     text NOT NULL,
    CONSTRAINT fk_branches_business
        FOREIGN KEY (business_id)
        REFERENCES businesses(id)
        ON DELETE CASCADE
);

CREATE TABLE users (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login           text NOT NULL UNIQUE,
    password_hash   text NOT NULL,
    role_id         bigint NOT NULL,
    branch_id       bigint,
    created_at      timestamptz NOT NULL DEFAULT now(),
    business_id     bigint NOT NULL,

    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id)
        REFERENCES roles(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_users_branch
        FOREIGN KEY (branch_id)
        REFERENCES branches(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_users_business
        FOREIGN KEY (business_id)
        REFERENCES businesses(id)
        ON DELETE CASCADE
);

CREATE TABLE employees (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id   bigint NOT NULL,
    name        text NOT NULL,
    surname     text NOT NULL,
    position    text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_employees_branch
        FOREIGN KEY (branch_id)
        REFERENCES branches(id)
        ON DELETE CASCADE
);

CREATE TABLE employee_schedules (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id  bigint NOT NULL,
    day_of_week  int NOT NULL,
    start_time   time NOT NULL,
    end_time     time NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_employee_schedules_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_employee_schedules_day_of_week
        CHECK (day_of_week BETWEEN 1 AND 7),

    CONSTRAINT chk_employee_schedules_time_range
        CHECK (start_time < end_time),

    CONSTRAINT uq_employee_schedule_unique_slot
        UNIQUE (employee_id, day_of_week, start_time, end_time)
);

CREATE TABLE services (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id         bigint NOT NULL,
    name              text NOT NULL,
    duration_minutes  int NOT NULL,
    price             numeric(10,2) NOT NULL,
    created_at        timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_services_branch
        FOREIGN KEY (branch_id)
        REFERENCES branches(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_services_duration
        CHECK (duration_minutes > 0),

    CONSTRAINT chk_services_price
        CHECK (price >= 0)
);

CREATE TABLE employee_services (
    employee_id bigint NOT NULL,
    service_id  bigint NOT NULL,

    PRIMARY KEY (employee_id, service_id),

    CONSTRAINT fk_employee_services_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_employee_services_service
        FOREIGN KEY (service_id)
        REFERENCES services(id)
        ON DELETE CASCADE
);

CREATE TABLE clients (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           text,
    phone           text,
    name            text NOT NULL,
    surname         text NOT NULL,
    tg_username     text,
    password_hash   text,
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_clients_email UNIQUE (email),
    CONSTRAINT uq_clients_phone UNIQUE (phone),
    CONSTRAINT uq_clients_tg_username UNIQUE (tg_username)
);

CREATE TABLE appointments (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   bigint NOT NULL,
    branch_id   bigint NOT NULL,
    employee_id bigint NOT NULL,
    service_id  bigint NOT NULL,
    start_time  timestamptz NOT NULL,
    end_time    timestamptz NOT NULL,
    status      text NOT NULL,
    comment     text,
    created_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_appointments_client
        FOREIGN KEY (client_id)
        REFERENCES clients(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_appointments_branch
        FOREIGN KEY (branch_id)
        REFERENCES branches(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_appointments_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_appointments_service
        FOREIGN KEY (service_id)
        REFERENCES services(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_appointments_time_range
        CHECK (start_time < end_time),

    CONSTRAINT chk_appointments_status
        CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled'))
);

CREATE INDEX idx_branches_business_id
    ON branches (business_id);

CREATE INDEX idx_users_role_id
    ON users (role_id);

CREATE INDEX idx_users_branch_id
    ON users (branch_id);

CREATE INDEX idx_users_business_id
    ON users (business_id);

CREATE INDEX idx_employees_branch_id
    ON employees (branch_id);

CREATE INDEX idx_employee_schedules_employee_id
    ON employee_schedules (employee_id);

CREATE INDEX idx_services_branch_id
    ON services (branch_id);

CREATE INDEX idx_appointments_client_id
    ON appointments (client_id);

CREATE INDEX idx_appointments_branch_id
    ON appointments (branch_id);

CREATE INDEX idx_appointments_employee_id
    ON appointments (employee_id);

CREATE INDEX idx_appointments_service_id
    ON appointments (service_id);

CREATE INDEX idx_appointments_start_time
    ON appointments (start_time);

CREATE INDEX idx_appointments_employee_start_time
    ON appointments (employee_id, start_time);
-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS employee_services;
DROP TABLE IF EXISTS employee_schedules;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS branches;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS businesses;
-- +goose StatementEnd