global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: auth
    metrics_path: /metrics
    static_configs:
      - targets: ["auth:8082"]

  - job_name: registration
    metrics_path: /metrics
    static_configs:
      - targets: ["registration:8081"]

  - job_name: branches
    metrics_path: /metrics
    static_configs:
      - targets: ["branches:8083"]

  - job_name: booking
    metrics_path: /metrics
    static_configs:
      - targets: ["booking:8084"]

  - job_name: bot
    metrics_path: /metrics
    static_configs:
      - targets: ["bot:8085"]
